# BES2402KM6017
# MUHAMMAD AMMAR IZZUDIN
# BEJS

name: Deploy ke Railway Prod ENV

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Menginstall NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Menginstall Packages
        run: npm i

      - name: Menginstall Railway CLI
        run: npm i -g @railway/cli

      - name: Menginstall Prisma
        run: npm i prisma

      - name: Menjalankan Migrasi
        run: | 
          export DATABASE_URL="${{ secrets.PROD_DATABASE_URL }}"
          npx prisma migrate deploy

      - name: Deploy ke Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROD_TOKEN }}
