### daftar
POST http://localhost:3000/api/v1/daftar
Content-Type: application/json

{
    "nama":"ammar",
    "email":"21102122@ittelkom-pwt.ac.id",
    "kata_sandi":"ammar123"
}

### masuk
POST http://localhost:3000/api/v1/masuk
Content-Type: application/json

{
    "email": "21102122@ittelkom-pwt.ac.id",
    "kata_sandi": "ammar19"
}

### minta verifikasi email
GET http://localhost:3000/api/v1/minta-verifikasi-email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE2Mjg0MDY1fQ.-UzVQTkMCpl3ZwiD-0ucarNRXCZee04T8QPeVOnXXbc

### lupa kata sandi
POST http://localhost:3000/api/v1/lupa-kata-sandi
Content-Type: application/json

{
    "email": "21102122@ittelkom-pwt.ac.id"
}

### reset kata sandi
POST http://localhost:3000/api/v1/reset-kata-sandi
Content-Type: application/json

{
    "kataSandiBaru": "ammar15",
    "konfirmasiKataSandi": "ammar15"
}

### welcome
GET http://localhost:3000/api/v1/welcome
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE2MjcxODE5fQ.cp4VFOK73qCHtZIOuryb__LiZ8Fb_Lamwxp6nDSeS1I

